version: '3.8'

services:
  db:
    image: postgres:16
    container_name: education-system
    restart: always
    environment:
      POSTGRES_DB: education_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: