spring.application.name=education-system
spring.datasource.url=jdbc:postgresql://localhost:5432/education_db
spring.datasource.username=your_username
spring.datasource.password=your_password

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#EXCEPTIONSINFO
#spring.web.error.include-message=always
